---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: debian/stretch64

suites:
  - name: default
    run_list:
      - recipe[sysctl::default]
    attributes:
  - name: test_attributes
    run_list:
      - recipe[sysctl::default]
    attributes:
      sysctl:
        settings:
          net.ipv4.ip_forward: "1"
